application/blueprints/base/views.py
from flask import Blueprint, abort, render_template
from sqlalchemy import text

from application.models import DatasetReport, Organisation

base = Blueprint("base", __name__)


@base.route("/")
@base.route("/index")
def index():
    lpas = Organisation.query.order_by(Organisation.name).all()
    return render_template("homepage.html", lpas=lpas)


@base.route("/organisation/<string:organisation>")
def org_summary(organisation):
    from application.extensions import db

    organisation = Organisation.query.get(organisation)
    if not organisation:
        abort(404)

    query = f"""
        SELECT d.dataset as dataset, r.resource as resource, o.organisation as organisation, r.start_date as start_date
        FROM dataset d, resource r, dataset_resource dr, organisation o, organisation_resource orgr
        WHERE d.dataset = dr.dataset
        AND r.resource = dr.resource
        AND dr.resource = orgr.resource
        AND o.organisation = orgr.organisation
        AND o.organisation = '{organisation.organisation}'
        ORDER BY d.dataset, r.start_date;
    """

    sql = text(query)
    results = db.session.execute(sql).fetchall()
    latest_resource_map = {}
    for result in results:
        dataset = result.dataset
        resource = result.resource
        start_date = result.start_date
        if dataset not in latest_resource_map:
            latest_resource_map[dataset] = {
                "resource": resource,
                "start_date": start_date,
            }
        else:
            if latest_resource_map[dataset]["start_date"] < start_date:
                latest_resource_map[dataset] = {
                    "resource": resource,
                    "start_date": start_date,
                }

    reports = []

    for item, data in latest_resource_map.items():
        resource = data.get("resource")
        r = DatasetReport.query.filter(
            DatasetReport.dataset_id == item,
            DatasetReport.resource_id == resource,
            DatasetReport.organisation_id == organisation.organisation,
        ).one_or_none()
        if r is not None:
            reports.append(r)

    last_update = None
    for report in reports:
        if last_update is None:
            last_update = report.created_date
        elif report.created_date > last_update:
            last_update = report.created_date

    return render_template(
        "organisation-summary.html",
        organisation=organisation,
        reports=reports,
        last_update=last_update,
    )


@base.route(
    "/organisation/<string:organisation>/<string:dataset>/<string:resource>/feedback"
)
def dataset_feedback(organisation, dataset, resource):

    report = DatasetReport.query.filter(
        DatasetReport.organisation_id == organisation,
        DatasetReport.dataset_id == dataset,
        DatasetReport.resource_id == resource,
    ).one_or_none()
    if report is None:
        abort(404)

    additions = []
    changes = []
    checks = []

    for issue in report.get_additions():
        additions.append(
            {
                "type": "mandatory",
                "field": issue.field,
                "description": issue.issue.issue_description,
            }
        )

    for issue in report.get_changes():
        changes.append(
            {
                "type": "recommendation",
                "field": issue.field,
                "description": issue.issue.issue_description,
            }
        )

    for issue in report.get_checks():
        checks.append(
            {
                "type": "recommendation",
                "field": issue.field,
                "description": issue.issue.issue_description,
            }
        )

    feedback = []
    if additions:
        feedback.append(
            {"title": "Add missing data", "type": "missing", "issues": additions}
        )
    if changes:
        feedback.append(
            {"title": "Change the data format", "type": "format", "issues": changes}
        )

    if checks:
        feedback.append(
            {"title": "Check accuracy of data", "type": "accuracy", "issues": checks}
        )

    return render_template(
        "dataset-feedback.html", report=report, interval="daily", feedback=feedback
    )

application/blueprints/check/views.py
import csv
import os
import tempfile

import requests
from digital_land import commands
from flask import Blueprint, abort, current_app, render_template, request

from application.blueprints.check.forms import CheckForm
from application.models import Dataset
from application.utils import Workspace, convert_resource

check = Blueprint("check", __name__)


@check.route("/check-your-data", methods=["GET", "POST"])
def check_data():
    form = CheckForm()
    if form.validate_on_submit():
        dataset = form.datasets.data
        url = form.url.data.strip()
        results = _run_pipeline(dataset, url)
        return render_template(
            "check-your-data.html", form=form, url=url, dataset=dataset, results=results
        )
    return render_template("check-your-data.html", form=form)


def _run_pipeline(dataset_id, resource_url):

    dataset = Dataset.query.get(dataset_id)
    DATASETTE = current_app.config["DATASETTE_URL"]
    fields_url = f"{DATASETTE}/digital-land/dataset_field.json?_shape=array&dataset__exact={dataset.dataset}"
    column_url = f"{DATASETTE}/digital-land/column.json?_shape=array&dataset__exact={dataset.dataset}"
    concat_url = f"{DATASETTE}/digital-land/concat.json?_shape=array&dataset__exact={dataset.dataset}"
    default_url = f"{DATASETTE}/digital-land/_default.json?_shape=array&dataset__exact={dataset.dataset}"
    try:
        resp = requests.get(fields_url)
        resp.raise_for_status()
        fields = [f["field"] for f in resp.json()]

        resp = requests.get(column_url)
        resp.raise_for_status()
        column = resp.json()

        resp = requests.get(concat_url)
        resp.raise_for_status()
        concat = resp.json()

        resp = requests.get(default_url)
        resp.raise_for_status()
        default = resp.json()

    except Exception as e:
        print(e)
        return "Could not run pipeline"

    dataset_config = {"column": column, "concat": concat, "default": default}

    with tempfile.TemporaryDirectory() as temp_dir:

        workspace = Workspace.factory(
            dataset,
            temp_dir,
            current_app.config["PROJECT_ROOT"],
            resource_url,
            dataset_config,
        )

        # Use digital land python to collect resource
        commands.collect(workspace.endpoint_csv, workspace.collection_dir)

        resources = os.listdir(workspace.resource_dir)

        if not resources:
            print("No resource collected")
            return abort(400)
        else:
            resource_hash = resources[0]
            limit = int(request.args.get("limit")) if request.args.get("limit") else 10
            (
                resource_fields,
                input_path,
                output_path,
                resource_rows,
            ) = convert_resource(workspace, resource_hash, limit)

            # Run API pipeline
            commands.pipeline(
                input_path,
                output_path,
                workspace.collection_dir,
                None,
                workspace.issue_dir,
                workspace.organisation_path,
                column_field_dir=workspace.column_field_dir,
                dataset_resource_dir=workspace.dataset_resource_dir,
                endpoints=["dummy-endpoint"],
            )

            issues = []
            issue_file = os.path.join(workspace.issue_dir, f"{resource_hash}.csv")
            with open(issue_file) as file:
                reader = csv.DictReader(file)
                for row in reader:
                    issues.append(row)

    # input path could be used to show user what we collected from url if useful?

    return {
        "issues": issues,
        "resource_fields": resource_fields,
        "specification_fields": fields,
        "converted_resource_rows": resource_rows,
    }

application/templates/check-your-data.html
{% extends "layouts/layout.html" %}
{% block pageTitle %}Check your data{% endblock %}
{% block content %}
  <main id="content" role="main">
    {%  if results %}
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
          <h1 class="govuk-heading-m">Results</h1>
          <dl class="govuk-summary-list">
            <div class="govuk-summary-list__row">
              <dt class="govuk-summary-list__key">
                URL
              </dt>
              {{ url }}
              </dd>
            </div>
            <div class="govuk-summary-list__row">
              <dt class="govuk-summary-list__key">
                Dataset
              </dt>
              {{ dataset }}
              </dd>
            </div>
          </dl>
        </div>
      </div>
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
          <pre class="govuk-!-margin-0"><code class="language-json"
                                                    style="overflow: scroll;">{{ results | dump_json }}</code></pre>
        </div>
      </div>
      <div class="govuk-grid-row">
        <a href="{{ url_for('check.check_data') }}" class="govuk-back-link">Back</a>
      </div>
    {% else %}
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
          <h1 class="govuk-heading-m">Check your data</h1>
        </div>
      </div>
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
          <form method="POST" action="{{ url_for('check.check_data') }}">
            <div class="govuk-form-group">
              {{ form.datasets.label(class="govuk-label") }}
              {{ form.datasets(class="govuk-select") }}
            </div>
            <div class="govuk-form-group">
              {{ form.url.label(class="govuk-label") }}
              {{ form.url(class="govuk-input") }}
            </div>
            <div class="govuk-button-group">
              <input class="govuk-button" type="submit" value="Check">
            </div>
            {{ form.csrf_token }}
          </form>
        </div>
      </div>
    {% endif %}
  </main>
{% endblock %}

application/templates/dataset-feedback.html
{% extends "layouts/layout.html" %}

{%- from 'govuk_frontend_jinja/components/table/macro.html' import govukTable -%}
{%- from 'govuk_frontend_jinja/components/tag/macro.html' import govukTag -%}
{%- from 'govuk_frontend_jinja/components/summary-list/macro.html' import govukSummaryList -%}
{%- from 'components/feedback/macro.html' import feedbackList as appFeedback with context -%}

{% block pageTitle %}{{ report.dataset.dataset }}{% endblock %}

{%- block breadcrumbs -%}
  {{- govukBreadcrumbs({
    "items": [
        {
          "text": "Feedback",
          "href": "/"
        },
        {
          "text": report.organisation.name,
          "href": "/organisation/" + report.organisation.organisation
        },
        {
          "text": report.dataset.name,
          "href": None
        }
    ]
    }) -}}
{%- endblock -%}

{% block content %}

  <main id="content" role="main">

    <div class="govuk-grid-row">
      <div class="govuk-grid-column-full">
        <h1 class="govuk-heading-xl govuk-!-margin-bottom-3">How to improve {{ report.dataset.name }} data from {{ report.organisation.name }}</h1>
      </div>
    </div>
  </div>

  <hr class="govuk-section-break govuk-section-break--m" aria-hidden="true">

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

        <h2 class="govuk-heading-l">Step by step feedback</h2>
        <p>The following steps are activities {{ report.organisation.name }} can do to ensure the {{ report.dataset.name }} data it publishes online meets the data standard and can be used by DLUHC and the general public.</p>

      {% set stepsOverviewHTML %}
        <p>Steps that must be completed are marked as mandatory.</p>
        <p>Steps that are not mandatory but will improve the value and accessibility of the data are marked as a recommendation.</p>
        <p>Clicking on a step will take you to a page showing more detail about what the feedback is and how to act upon it.</p>
      {% endset %}

      {{
        govukDetails({
          'summaryText': 'How to follow these steps',
          'html': stepsOverviewHTML,
          'classes': 'govuk-!-margin-bottom-8'
        })
      }}

        {{
          appFeedback({'list': feedback })
        }}


        <hr class="govuk-section-break govuk-section-break--m" aria-hidden="true">

        {# this should probably be a component driven by data? #}
{#        <nav class="app-pagination" role="navigation" aria-label="Pagination">#}
{#            <div class="app-pagination__button app-pagination__button--next">#}
{#                <a href="#" class="app-pagination__link" rel="next">#}
{#                    <span class="app-pagination__link-title">#}
{#                        <span class="app-pagination__link-label">#}
{#                            Next<span class="govuk-visually-hidden"> dataset</span>#}
{#                        </span>#}
{#                    </span>#}
{#                    <span class="app-pagination__link-text">{{ '{{ dataset name here }}' }}</span>#}
{#                </a>#}
{#            </div>#}
{#            <div class="app-pagination__button app-pagination__button--previous">#}
{#                <a href="#" class="app-pagination__link" rel="prev">#}
{#                    <span class="app-pagination__link-title">#}
{#                        <span class="app-pagination__link-label">#}
{#                            Previous<span class="govuk-visually-hidden"> dataset</span>#}
{#                        </span>#}
{#                    </span>#}
{#                    <span class="app-pagination__link-text">{{ '{{ dataset name here }}' }}</span>#}
{#                </a>#}
{#            </div>#}
{#        </nav>#}

        <hr class="govuk-section-break govuk-section-break--m" aria-hidden="true">

      </div>
      <!-- / .govuk-grid-column-two-thirds -->

      <div class="govuk-grid-column-one-third">
        <h3 class="govuk-heading-s">About this feedback</h3>
        <p class="govuk-!-font-size-16">This feedback was last updated<br> {{ report.created_date | short_date }}.</p>
        <p class="govuk-!-font-size-16">This feedback is updated {{ interval }}.</p>
        <p class="govuk-!-font-size-16">If need support you can <a href="#">contact the Planning Data team</a>.</p>
      </div>

    </div>
    <!-- / .govuk-grid-column-two-thirds -->

    <div class="govuk-grid-column-one-third">
      <h3 class="govuk-heading-s">About this feedback</h3>
      <p class="govuk-!-font-size-16">This feedback was last updated<br> {{ '{{ date }}' }}.</p>
      <p class="govuk-!-font-size-16">This feedback is updated {{ '{{ interval }}' }}.</p>
      <p class="govuk-!-font-size-16">If need support you can <a href="#">contact the Planning Data team</a>.</p>
    </div>

  </div>

{% endblock %}

{% block bodyEnd %}
  {{ super() }}
{% endblock bodyEnd %}

application/templates/homepage.html
{% extends "layouts/layout.html" %}

{%- from 'govuk_frontend_jinja/components/table/macro.html' import govukTable -%}
{%- from 'govuk_frontend_jinja/components/tag/macro.html' import govukTag -%}

{% block pageTitle %}Feedback{% endblock %}

{% block content %}
  {% if not lpas %}
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-xl govuk-!-margin-bottom-5">Help to publish your planning and housing data</h1>
        <p class="govuk-body-l govuk-!-margin-bottom-6">
          Application data is being loaded. Check back here in a few minutes.
        </p>
      </div>
    </div>
  {% else %}
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h1 class="govuk-heading-xl govuk-!-margin-bottom-5">Help to publish your planning and housing data</h1>
      <p class="govuk-body-l govuk-!-margin-bottom-6">
        Get feedback and support to publish data that meets standards set by the Department for Levelling Up, Housing and Communities.</p>
    </div>
  </div>

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <form class="govuk-!-margin-bottom-6">
        <label class="govuk-label govuk-label--m govuk-!-font-weight-bold" for="filter-organisations-list">Search for your organisation</label>
        <input class="govuk-input" type="text" id="filter-organisations-list" placeholder="For example, Lambeth">
      </form>
    </div>
    <!-- /. govuk-grid-column-two-thirds -->
    <div class="govuk-grid-column-full">
      <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">
    </div>
    <!-- /. govuk-grid-column-full -->
  </div>
  <!-- /. govuk-grid-row -->

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
      {% set letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" | list %}
      {% for char in letters %}
        {% set theseLPAs = lpas | get_items_beginning_with(char) %}
        {% if (theseLPAs | length) > 0 %}
          <div class="govuk-grid-row js-filter-item">
            <div class="govuk-grid-column-one-third">
              <h2 class="govuk-heading-xl">{{ char }}</h2>
            </div>
            <div class="govuk-grid-column-two-thirds">
              <ul class="govuk-list govuk-!-margin-bottom-0">
                {% for lpa in theseLPAs  %}
                  <li class="govuk-!-margin-bottom-1 js-filter-item">
                    <a href="{{url_for('base.org_summary', organisation=lpa.organisation)}}" class="govuk-link">{{ lpa.name }}</a>
                  </li>
                {% endfor %}
              </ul>
            </div>
            <div class="govuk-grid-column-full">
              <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">
            </div>
          </div>
          <!-- /.govuk-grid-row -->
        {% endif %}
      {% endfor %}
    </div>
  </div>
  {% endif %}
{% endblock %}

{% block bodyEnd %}
  {# this needs refactoring and abstracting to a component #}
  <script>
    let filterItems = document.querySelectorAll('.js-filter-item')
    function liveSearch() {
        let search_query = document.getElementById("filter-organisations-list").value;
        //Use innerText if all contents are visible
        //Use textContent for including hidden elements
        for (var i = 0; i < filterItems.length; i++) {
            if(filterItems[i].textContent.toLowerCase()
                    .includes(search_query.toLowerCase())) {
                filterItems[i].classList.remove("govuk-visually-hidden");
            } else {
                filterItems[i].classList.add("govuk-visually-hidden");
            }
        }
    }
    //A little delay
    let typingTimer;
    let typeInterval = 500;
    let searchInput = document.getElementById('filter-organisations-list');
    searchInput.addEventListener('keyup', () => {
        clearTimeout(typingTimer);
        typingTimer = setTimeout(liveSearch, typeInterval);
    });
  </script>
  {{ super() }}
{% endblock bodyEnd %}

application/templates/organisation-summary.html
{% extends "layouts/layout.html" %}
{%- from 'govuk_frontend_jinja/components/table/macro.html' import govukTable -%}
{%- from 'govuk_frontend_jinja/components/tag/macro.html' import govukTag -%}
{% block pageTitle %}Feedback for {{ 'organisation' }}{% endblock %}

{%- block breadcrumbs -%}
  {{- govukBreadcrumbs({
    "items": [
        {
          "text": "Feedback",
          "href": "/"
        },
        {
          "text": organisation.name | default('Organisation'),
          "href": "#top"
        }
    ]
    }) -}}
{%- endblock -%}

{% block content %}

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <span class="govuk-caption-xl">Organisation</span>
      <h1 class="govuk-heading-xl govuk-!-margin-bottom-5">{{ organisation.name }}</h1>
      <p class="govuk-body-l">Feedback to help your organisation publish planning data.</p>
    </div>
    <div class="govuk-grid-column-two-thirds">
    <hr class="govuk-section-break govuk-section-break--l govuk-!-margin-top-0 govuk-section-break--visible">
    </div>
  </div>

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <p>The following is a list of the datasets DLUHC creates using data published by {{ organisation.name | default('this organisation') }} with a status from the last time data was collected.</p>

{#        {% set confObj = {#}
{#          'status' : {#}
{#            'actions' : govukTag({ 'text': 'Action needed', 'classes': 'govuk-tag--error' }),#}
{#            'recommendations': govukTag({ 'text': 'Has recommendations','classes': 'govuk-tag--blue' }),#}
{#            'good': govukTag({ 'text': 'Standard met', 'classes': 'govuk-tag--green' })#}
{#          }#}
{#        } %}#}

        <table class="govuk-table">
          <thead class="govuk-table__head">
          <tr class="govuk-table__row">
            <th scope="col" class="govuk-table__header">Dataset</th>
            <th scope="col" class="govuk-table__header govuk-table__header--numeric">Status</th>
          </tr>
          </thead>

          <tbody class="govuk-table__body">
            {% for report in reports %}
              <tr class="govuk-table__row">
                <td class="govuk-table__cell">
                  <a href="{{ url_for('base.dataset_feedback', organisation=report.organisation_id, dataset=report.dataset_id, resource=report.resource_id) }}">{{ report.dataset.name }}</a>
                </td>
                <td class="govuk-table__cell govuk-table__cell--numeric">
                  {% if report.has_actions() %}
                    <strong class="govuk-tag govuk-tag--error">
                    Action needed
                    </strong>
                  {% elif report.has_recommendations() %}
                    <strong class="govuk-tag govuk-tag--blue">
                      Has recommendations
                    </strong>
                  {%  else %}
                    <strong class="govuk-tag govuk-tag--green">
                      Standard met
                    </strong>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

        <p class="govuk-!-font-size-16">This page was last updated {{ last_update | short_date }}</p>

      </div>

    </div>
  </div>
{% endblock %}

{% block bodyEnd %}
  {{ super() }}
{% endblock bodyEnd %}